//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ConfigPanel {
            get {
                object obj = ResourceManager.GetObject("ConfigPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_bg {
            get {
                object obj = ResourceManager.GetObject("crystal_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_list_bg {
            get {
                object obj = ResourceManager.GetObject("crystal_list_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_list_focus {
            get {
                object obj = ResourceManager.GetObject("crystal_list_focus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_overlay_all {
            get {
                object obj = ResourceManager.GetObject("crystal_overlay_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_overlay_all_dark {
            get {
                object obj = ResourceManager.GetObject("crystal_overlay_all_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_overlay_bottom {
            get {
                object obj = ResourceManager.GetObject("crystal_overlay_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystal_overlay_top_dark {
            get {
                object obj = ResourceManager.GetObject("crystal_overlay_top_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crystalback {
            get {
                object obj = ResourceManager.GetObject("crystalback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] CrystalFonts {
            get {
                object obj = ResourceManager.GetObject("CrystalFonts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalFontsSmall {
            get {
                object obj = ResourceManager.GetObject("CrystalFontsSmall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalLayoutCoverflow {
            get {
                object obj = ResourceManager.GetObject("CrystalLayoutCoverflow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalLayoutDetails {
            get {
                object obj = ResourceManager.GetObject("CrystalLayoutDetails", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalLayoutPoster {
            get {
                object obj = ResourceManager.GetObject("CrystalLayoutPoster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalLayoutThumb {
            get {
                object obj = ResourceManager.GetObject("CrystalLayoutThumb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalLayoutThumbStrip {
            get {
                object obj = ResourceManager.GetObject("CrystalLayoutThumbStrip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalListView {
            get {
                object obj = ResourceManager.GetObject("CrystalListView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalMediaInfoPanel {
            get {
                object obj = ResourceManager.GetObject("CrystalMediaInfoPanel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalMovieView {
            get {
                object obj = ResourceManager.GetObject("CrystalMovieView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalPagination {
            get {
                object obj = ResourceManager.GetObject("CrystalPagination", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalTab {
            get {
                object obj = ResourceManager.GetObject("CrystalTab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CrystalToolBox {
            get {
                object obj = ResourceManager.GetObject("CrystalToolBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Images {
            get {
                object obj = ResourceManager.GetObject("Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LayoutRoot {
            get {
                object obj = ResourceManager.GetObject("LayoutRoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageCrystal {
            get {
                object obj = ResourceManager.GetObject("PageCrystal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PageDetailAreaCrystal {
            get {
                object obj = ResourceManager.GetObject("PageDetailAreaCrystal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PersonButton {
            get {
                object obj = ResourceManager.GetObject("PersonButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
